### ISSUE TITLE
How to apply affine matrix +  diffeomorphic warp matrix to external image

### ISSUE THREAD

**Issue by grenkoca** [CBICA/HistoReg#19]
Hi all,

Right now I'm working with HistoReg to register TMA cores. Due to the differential staining, different tissues within the two cores attract the DAB which leads to misalignment when I run the whole core for registration. To get around this, I use stain deconvolution to extract the Hematoxylin intensities, then register the two deconvolved cores together. This leads to a great registration, but no DAB. 

I know that in the registration, it outputs the affine matrix (`Affine.mat`) and the full-size diffeomorphic warp field ( `big_warp.nii.gz`). How would I independently reslice the full-size moving image with these transformation matrices?

From what I understand, HistoReg goes through the following steps:
1) Pad source image to match dimensions of target
2) Find rough affine registration --> Affine.mat
3) Find diffeomorphic registration --> big_warp.nii.gz

Then it loads the source image and applies these transformations through reslicing. How would I do that on my own given an image and these matrices? Alternatively, does HistoReg support something along the lines of reslicing a different image than the matrices were found on (or even more specifically finding the transformations on the deconvolved image and applying them to the original image)

Thanks,
Caleb

**Comment by ludovenet** [comment]
Hi Caleb,

You are totally right, as explained in our paper, the DAB stain can lead to misalignments and the use of stain deconvolution allow your to extract the DAB component from the image and perform better registration. Once the transformations are computed with the stain deconvolved images, you can apply them to the original images (with the DAB component) and obtain good registration.

For now, HistoReg doesn't support this and you have to manually perform those steps. This might be added in the future, I will let you know.

What you can do is :  
 1. Perform color deconvolution on the DAB image.
 2. Run HistoReg with the color deconvolved images and get the transformations files (Affine.mat and big_warp.nii.gz)
 3. Apply those transformation to the original moving image using "greedy". Doc [here](https://sites.google.com/view/greedyreg/documentation?authuser=0)

For 3. the command you run should be like this : 
path/to/greedy_executable -d 2 \
	-rf path/to/original/target/image \
	-rm path/to/original/moving/image path/to/output/image \
	-r path/to/big_warp.nii.gz path/to/Affine.mat

Let me know if you have any trouble with this, I would be happy to help.

**Comment by grenkoca** [comment]
Hi Ludo, I've actually implemented this in my own branch for full resolution images. If you pass a separate '-rs [img path]' arg to HistoReg and are using full size images, it calculates the registration on the -m image and executes them on the -rs image. Have a look: https://github.com/grenkoca/HistoReg  

I figured it's niche enough functionality that it isn't worth adding to the main repo, but should I issue a pull request?

**Comment by ludovenet** [comment]
Hi Caleb,

That's great ! I just had the time to have a quick look through your code and this should be working fine.
It doesn't cost anything and could help some users, so I think we should add this feature to the main repo. I will try it when I have more time and update the help menu and the "read me" accordingly. I'm very busy for the next two weeks, but I'll take a look at it as soon as I can.

Thanks again, will let you know about this.
I'm closing this issue, feel free to reopen if needed.
