### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by phiwei** [CBICA/HistoReg#2]
Hi, 

thank you very much for making your contribution publicly available. I would like to try it on some data that I have but unfortunately, I am having difficulties installing the programme. When running
`cmake --build . --target ALL_BUILD `
I get the error
`make: *** No rule to make target 'ALL_BUILD'.  Stop.`

If I run the consecutive steps of the installation without this one, 
`cmake -DCMAKE_INSTALL_PREFIX=$"/my_dir/HistoReg" .. `
fails with 
`CMake Error: The source directory "/my_dir/HistoReg" does not appear to contain CMakeLists.txt.`

I am using gcc 7.4.0 and cmake 3.10.2. 
Do you have any idea how to fix this? 

Best wishes
Philippe

**Comment by sarthakpati** [comment]
Hi @phiwei, thank you for your interest in HistoReg!

Those instructions are specifically for Windows. You can try just running ```make``` after the CMake configure step to compile and then ```make install/strip``` to perform the installation. I have added a new section in the documentation for this: https://github.com/CBICA/HistoReg/blob/master/README.md#linux

**Comment by phiwei** [comment]
Hi, 
thank you for updating the instructions. Everything seems to be working fine until
`make install/strip`
I get the error 
`make: *** No rule to make target 'install/strip'.  Stop.`
Although the `make` step seemed successful with corresponding update messages, the target directory is empty, is this the expected behaviour? 
Thanks!

**Comment by sarthakpati** [comment]
Can you try ```make install```?

**Comment by phiwei** [comment]
I tried that as well, also `make install-strip` with the same error message except for the specified part before the `Stop.`

**Comment by sarthakpati** [comment]
> Is it correct to execute the install command from the bin directory?

Yes.

> I am out of office now but can try more things tomorrow morning.

Please let me know after you have tried it.

**Comment by phiwei** [comment]
I had already tried `make install` earlier today and it failed.

**Comment by sarthakpati** [comment]
Unsure how it was happening:

```bash
[SNIP!]
[ 92%] Linking CXX static library libGREEDY_LIB.a
[ 92%] Built target GREEDY_LIB
[100%] Linking CXX executable HistoReg
[100%] Built target HistoReg
(base) patis@/cbica/home/patis/testing/HistoReg/bin>$ make install/strip
[ 53%] Built target HistoReg
[100%] Built target GREEDY_LIB
Installing the project stripped...
-- Install configuration: ""
-- Installing: /cbica/home/patis/testing/HistoReg/bin/install/bin/HistoReg
(base) patis@/cbica/home/patis/testing/HistoReg/bin>$ ls install/bin/
HistoReg*
```

Do you mind deleting the repo and whatever you have built and trying again? Thanks.

**Comment by sarthakpati** [comment]
No worries! The segmentation fault is something the developer of the algorithm could help with (@ludovenet).
