### ISSUE TITLE
Errors happen in compilation on linux

### ISSUE THREAD

**Issue by elephanttt** [CBICA/HistoReg#23]
When I finished ITK building and run “make -j8” for HistoReg， I got the error：
libGREEDY_LIB.a(GreedyAPI.cxx.o): In function `GreedyApproach<2u, float>::RunDeformable(GreedyParameters&)':
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj2EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj2EfE13RunDeformableER16GreedyParameters]+0x6dd): undefined reference to `LDDMMData<float, 2u>::poisson_pde_zero_boundary_initialize(itk::ImageBase<2u>*, itk::Image<float, 2u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj2EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj2EfE13RunDeformableER16GreedyParameters]+0x1643): undefined reference to `LDDMMData<float, 2u>::poisson_pde_zero_boundary_solve(void*, itk::Image<float, 2u>*, itk::Image<float, 2u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj2EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj2EfE13RunDeformableER16GreedyParameters]+0x1c43): undefined reference to `LDDMMData<float, 2u>::poisson_pde_zero_boundary_dealloc(void*)'
libGREEDY_LIB.a(GreedyAPI.cxx.o): In function `GreedyApproach<3u, float>::RunDeformable(GreedyParameters&)':
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj3EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj3EfE13RunDeformableER16GreedyParameters]+0x709): undefined reference to `LDDMMData<float, 3u>::poisson_pde_zero_boundary_initialize(itk::ImageBase<3u>*, itk::Image<float, 3u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj3EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj3EfE13RunDeformableER16GreedyParameters]+0x1690): undefined reference to `LDDMMData<float, 3u>::poisson_pde_zero_boundary_solve(void*, itk::Image<float, 3u>*, itk::Image<float, 3u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj3EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj3EfE13RunDeformableER16GreedyParameters]+0x1c90): undefined reference to `LDDMMData<float, 3u>::poisson_pde_zero_boundary_dealloc(void*)'
libGREEDY_LIB.a(GreedyAPI.cxx.o): In function `GreedyApproach<4u, float>::RunDeformable(GreedyParameters&)':
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj4EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj4EfE13RunDeformableER16GreedyParameters]+0x6f5): undefined reference to `LDDMMData<float, 4u>::poisson_pde_zero_boundary_initialize(itk::ImageBase<4u>*, itk::Image<float, 4u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj4EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj4EfE13RunDeformableER16GreedyParameters]+0x167e): undefined reference to `LDDMMData<float, 4u>::poisson_pde_zero_boundary_solve(void*, itk::Image<float, 4u>*, itk::Image<float, 4u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj4EfE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj4EfE13RunDeformableER16GreedyParameters]+0x1c7e): undefined reference to `LDDMMData<float, 4u>::poisson_pde_zero_boundary_dealloc(void*)'
libGREEDY_LIB.a(GreedyAPI.cxx.o): In function `GreedyApproach<2u, double>::RunDeformable(GreedyParameters&)':
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj2EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj2EdE13RunDeformableER16GreedyParameters]+0x70f): undefined reference to `LDDMMData<double, 2u>::poisson_pde_zero_boundary_initialize(itk::ImageBase<2u>*, itk::Image<double, 2u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj2EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj2EdE13RunDeformableER16GreedyParameters]+0x16a1): undefined reference to `LDDMMData<double, 2u>::poisson_pde_zero_boundary_solve(void*, itk::Image<double, 2u>*, itk::Image<double, 2u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj2EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj2EdE13RunDeformableER16GreedyParameters]+0x1cab): undefined reference to `LDDMMData<double, 2u>::poisson_pde_zero_boundary_dealloc(void*)'
libGREEDY_LIB.a(GreedyAPI.cxx.o): In function `GreedyApproach<3u, double>::RunDeformable(GreedyParameters&)':
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj3EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj3EdE13RunDeformableER16GreedyParameters]+0x6e9): undefined reference to `LDDMMData<double, 3u>::poisson_pde_zero_boundary_initialize(itk::ImageBase<3u>*, itk::Image<double, 3u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj3EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj3EdE13RunDeformableER16GreedyParameters]+0x166a): undefined reference to `LDDMMData<double, 3u>::poisson_pde_zero_boundary_solve(void*, itk::Image<double, 3u>*, itk::Image<double, 3u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj3EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj3EdE13RunDeformableER16GreedyParameters]+0x1c74): undefined reference to `LDDMMData<double, 3u>::poisson_pde_zero_boundary_dealloc(void*)'
libGREEDY_LIB.a(GreedyAPI.cxx.o): In function `GreedyApproach<4u, double>::RunDeformable(GreedyParameters&)':
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj4EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj4EdE13RunDeformableER16GreedyParameters]+0x6e9): undefined reference to `LDDMMData<double, 4u>::poisson_pde_zero_boundary_initialize(itk::ImageBase<4u>*, itk::Image<double, 4u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj4EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj4EdE13RunDeformableER16GreedyParameters]+0x166e): undefined reference to `LDDMMData<double, 4u>::poisson_pde_zero_boundary_solve(void*, itk::Image<double, 4u>*, itk::Image<double, 4u>*)'
GreedyAPI.cxx:(.text._ZN14GreedyApproachILj4EdE13RunDeformableER16GreedyParameters[_ZN14GreedyApproachILj4EdE13RunDeformableER16GreedyParameters]+0x1c78): undefined reference to `LDDMMData<double, 4u>::poisson_pde_zero_boundary_dealloc(void*)'
collect2: error: ld returned 1 exit status
CMakeFiles/HistoReg.dir/build.make:248: recipe for target 'HistoReg' failed
make[2]: *** [HistoReg] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/HistoReg.dir/all' failed
make[1]: *** [CMakeFiles/HistoReg.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error  2

**Comment by sarthakpati** [comment]
What version of ITK did you build?

**Comment by elephanttt** [comment]
5.2.0

**Comment by sarthakpati** [comment]
ITK 5.2.0 is not currently supported in HistoReg. Please follow the instructions in https://github.com/CBICA/HistoReg#linux by compiling ITK from scratch.

**Comment by elephanttt** [comment]
I did follow the instructions.

**Comment by sarthakpati** [comment]
Hi,

If ITK is build from the Superbuild (the first `make` command in the instructions [[ref](https://github.com/CBICA/HistoReg#linux)]), it should build 4.13.1 [[ref](https://github.com/CBICA/HistoReg/blob/master/cmake_modules/External-ITK.cmake#L22)]. Could you give the exact steps you followed so that we can replicate on our end?

**Comment by elephanttt** [comment]
Thank you, I got it. Due to the slow clone speed, I manually downloaded relevant files from the web page and add it.  By the way,  is there any  requirement for cmake version?

**Comment by elephanttt** [comment]
I have compiled ITK-4.13.2 from scratch, but the same error still exists.

**Comment by elephanttt** [comment]
Thank you for your help. I change the cmake version from 3.9 to 3.19. it works.

**Comment by sarthakpati** [comment]
Thanks for letting us know!
