### ISSUE TITLE
Windows Installation

### ISSUE THREAD

**Issue by phiwei** [CBICA/HistoReg#3]
Hi, 

is it possible that in the guide for the Windows installation, the 
`cd ..`
is incorrect? If I remove it, compilation, building and installation seem to succeed. 

When running the example though, I get a quite unspecific error message: 
`Segmentation fault`
without further specification. 

Best wishes
Philippe

**Comment by sarthakpati** [comment]
You are right! I have fixed it.

**Comment by sarthakpati** [comment]
When you run the example, have you performed the installation?

**Comment by phiwei** [comment]
Yes, I performed all steps that are listed in the installation guide.

**Comment by sarthakpati** [comment]
@ludovenet will you be able to shed some light to this?

**Comment by sarthakpati** [comment]
Closing this in favor of #4
