### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by phiwei** [CBICA/HistoReg#4]
Hi, 

so both for my windows, as well as my linux installation, I am getting a 
`Segmentation fault`
error message. On windows, only this gets printed, on Linux, I get
`Starting...
Reading arguments...
Done.
Creating output and temporary directories...
Done.
Segmentation fault (core dumped)`

Looking at the project code, I assume that for some reason, the program runs through a little further on Linux because of this. I tried both the nightly and stable build of c2d. 

@sarthakpati mentioned that you might have insights here, @ludovenet ?

Edit: this also happens if I specify a temporary directory manually. 

Best wishes
Philippe

**Comment by ludovenet** [comment]
Hi Philippe,

Thank you for your interest in HistoReg. 

It seems your error is due to an ITK function. 
What version of ITK do you use ? Are you sure it is compiled without errors ? Did you use it for other program ?

**Comment by phiwei** [comment]
Hi, 

thanks for getting back to me. The ITK version is the one that gets compiled during the installation process in the guidelines. If I am not mistaken, that should be version 4.13.2, at least that is what I conclude from the folder names in the ITK directory within HistoReg - if this is not plausible, I can check again. 

I do not use ITK for other purposes. During the process lined out in the guidelines, there are some warnings but no critical failures - it is still possible though that the process does not fully succeed. 

1. How can I check whether ITK compiled directly?
2. Can I download ITK from somewhere instead of building it myself? If so, to what folder would I need to paste it?

Best wishes
Philippe

**Comment by ludovenet** [comment]
It should work perfectly if you installed ITK with our installer, so there is no point of compiling ITK individually. 
I am currently out of town with limited access to my computer. My holidays end this week end, I should be able to have more time to look into this next week, I will let you know when I have something new.

Best regards,
Ludovic.

**Comment by sarthakpati** [comment]
> 1. How can I check whether ITK compiled correctly?

If HistoReg got compiled, then it means that it was able to detect and link against ITK properly, which means that ITK was built properly.

**Comment by sarthakpati** [comment]
Hi Philippe,

Have you had a chance to try HistoReg's new release(s)? They make the process much easier to run and you don't need any further run-time installations. 

Cheers!

**Comment by phiwei** [comment]
Hi, 

thanks for pointing this out, I will see how it works in a month or two when I have some time!

Best wishes 
Philippe

**Comment by sarthakpati** [comment]
Alright! I am closing this issue, for now. If you run into further problems, please re-open or open a new one. 😄

**Comment by erexhepa** [comment]
Hi,

I was wondering if you could help with this issue as I do have the same problem. Just to answer the questions above, I am compiling ITK using the make shared in the git repository and everything goes smoothly. By the way I am getting the issue with the example images shared in the Data directory.

Thanks
Elton

**Comment by erexhepa** [comment]
I manage to find a solution to the first "Segmentation fault" error. It appear $HistoReg variable it is not initialized properly during installation. If you use full paths it manages to start but there is still a "Segmentation fault" due to c2d executable. It is not found. Can you advise on how to install it ?

Best
Elton

**Comment by sarthakpati** [comment]
Hi Elton,

Thanks for your interest in HistoReg!

Have you followed the superbuild recipe as mentioned in https://github.com/CBICA/HistoReg#windows or https://github.com/CBICA/HistoReg#linux?

The first `make` should compile ITK and the second should compile `HistoReg` and `c2d`...

**Comment by erexhepa** [comment]
Thak you very much for your quick feedback. Yeah I just realized I did a mistake on the second make (which would explain why HistoReg env variable was not setup properly). I am re-installing it again. Will give an update when I am finished.

**Comment by sarthakpati** [comment]
Awesome!

**Comment by erexhepa** [comment]
For the second cmake can I give as a prefix the same directory cloned from github ? If I want to install it in the same directory as ITK and all the other things that were build during the first cmake.

**Comment by erexhepa** [comment]
Thank you again for your assistance. By choosing the git repo to build the second make. It is working. Thank you for your work. Very useful.

**Comment by sarthakpati** [comment]
Glad to hear that it worked! If you publish your research please consider citing [our paper](https://github.com/CBICA/HistoReg/#citation).
